### PR TITLE
Rework audio handling for banners

### PR DESCRIPTION
**Pull request by Herrie82**
Largely based on
https://github.com/openwebos/luna-sysmgr/blob/master/Src/lunaui/notifications/BannerMessageHandler.cpp#L696
and
https://github.com/openwebos/luna-sysmgr/blob/1393f0af5dd8d9f0e9cc79627f4acb226f8c8d45/Src/base/LsmUtils.cpp#L45
converted to JS and made suitable for LNC.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Tofee** [comment]
Could you already test it, or should I validate it first ?

**Comment by Herrie82** [comment]
All cases worked except for the one where I made the luna-webappmgr PR for. I added the test cases to Testr app as well (ah wait I remember I forgot the .wav there, let me add it in the PR) :)

**Comment by Herrie82** [comment]
OK Testr PR is fine now.

**Comment by Herrie82** [comment]
This is my log without the luna-webappmgr PR: https://bpaste.net/show/02b1bdbce535 

As you can see all 5 scenarios from Testr are there. Just 2nd one is incorrect due to the prepend of the path in luna-webappmgr.

**Pull request merged**
